import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  usage: [{ type: "autogenerated", dirName: "usage" }],
  api: [
    { type: "doc", id: "api/index", label: "Overview" },
    {
      type: "category",
      label: "Functions",
      items: [{ type: "autogenerated", dirName: "api/functions" }],
    },
    {
      type: "category",
      label: "Types",
      items: [
        { type: "autogenerated", dirName: "api/interfaces" },
        { type: "autogenerated", dirName: "api/type-aliases" },
      ],
    },
    {
      type: "category",
      label: "Variables",
      items: [{ type: "autogenerated", dirName: "api/variables" }],
    },
  ],
}

export default sidebars
