import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docs: [{ type: "autogenerated", dirName: "." }],
  usage: ["usage/index"],
  api: ["api/index"],
  docs: [{ type: "autogenerated", dirName: "." }],
  // docs: [
  //   {
  //     type: "category",
  //     label: "Guides",
  //     link: {
  //       type: "generated-index",
  //       title: "Docusaurus Guides",
  //       description: "Learn about the most important Docusaurus concepts!",
  //       slug: "/category/docusaurus-guides",
  //       keywords: ["guides"],
  //       image: "/img/docusaurus.png",
  //     },
  //     items: ["pages", "docs", "blog", "search"],
  //   },
  // ],
  // usage: [{ type: "autogenerated", dirName: "usage" }],
  // api: [{ type: "autogenerated", dirName: "api" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

export default sidebars
